// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1, arg2) {
  return window['go']['backend']['App']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['backend']['App']['BuildSucess'](arg1);
}

export function DownloadUpgradeFile(arg1) {
  return window['go']['backend']['App']['DownloadUpgradeFile'](arg1);
}

export function GetCachedS3Client(arg1) {
  return window['go']['backend']['App']['GetCachedS3Client'](arg1);
}

export function GetTimeoutContext() {
  return window['go']['backend']['App']['GetTimeoutContext']();
}

export function InitAndCacheS3Client(arg1) {
  return window['go']['backend']['App']['InitAndCacheS3Client'](arg1);
}

export function QueryEncryptionKey() {
  return window['go']['backend']['App']['QueryEncryptionKey']();
}
