// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {s3} from '../models';
import {context} from '../models';

export function BuildFailed(arg1:string,arg2:string):Promise<models.BaseResponse>;

export function BuildSucess(arg1:any):Promise<models.BaseResponse>;

export function DownloadUpgradeFile(arg1:models.DownloadUpgradeFileReq):Promise<models.BaseResponse>;

export function GetCachedS3Client(arg1:string):Promise<s3.Client>;

export function GetTimeoutContext():Promise<context.Context|context.CancelFunc>;

export function InitAndCacheS3Client(arg1:string):Promise<s3.Client>;

export function QueryEncryptionKey():Promise<string>;
