// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Bucket']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Bucket']['BuildSucess'](arg1);
}

export function Init() {
  return window['go']['service']['Bucket']['Init']();
}

export function InitAndCacheS3Client(arg1) {
  return window['go']['service']['Bucket']['InitAndCacheS3Client'](arg1);
}

export function ListBuckets(arg1) {
  return window['go']['service']['Bucket']['ListBuckets'](arg1);
}

export function QueryEncryptionKey() {
  return window['go']['service']['Bucket']['QueryEncryptionKey']();
}
