// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomBucket(arg1) {
  return window['go']['service']['Bucket']['AddCustomBucket'](arg1);
}

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Bucket']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Bucket']['BuildSucess'](arg1);
}

export function CreateBucket(arg1) {
  return window['go']['service']['Bucket']['CreateBucket'](arg1);
}

export function DeleteBucket(arg1) {
  return window['go']['service']['Bucket']['DeleteBucket'](arg1);
}

export function FixDatabaseLockd() {
  return window['go']['service']['Bucket']['FixDatabaseLockd']();
}

export function GetBucketInfo(arg1) {
  return window['go']['service']['Bucket']['GetBucketInfo'](arg1);
}

export function GetCachedS3Client(arg1) {
  return window['go']['service']['Bucket']['GetCachedS3Client'](arg1);
}

export function GetTimeoutContext() {
  return window['go']['service']['Bucket']['GetTimeoutContext']();
}

export function Init() {
  return window['go']['service']['Bucket']['Init']();
}

export function InitAndCacheS3Client(arg1) {
  return window['go']['service']['Bucket']['InitAndCacheS3Client'](arg1);
}

export function InitDbClient() {
  return window['go']['service']['Bucket']['InitDbClient']();
}

export function ListBuckets(arg1) {
  return window['go']['service']['Bucket']['ListBuckets'](arg1);
}

export function QueryEncryptionKey() {
  return window['go']['service']['Bucket']['QueryEncryptionKey']();
}

export function ServiceName() {
  return window['go']['service']['Bucket']['ServiceName']();
}
