// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BuildFailed(arg1:string,arg2:string):Promise<any>;

export function BuildSucess(arg1:any):Promise<any>;

export function GetSavedConnectionList():Promise<any>;

export function GetTimeoutContext():Promise<context.Context>;

export function Init():Promise<void>;

export function InitAndCacheS3Client(arg1:string):Promise<any>;

export function QueryEncryptionKey():Promise<string>;

export function SaveS3Connection(arg1:any):Promise<any>;

export function TestS3Connection(arg1:any):Promise<any>;
