// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Connection']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Connection']['BuildSucess'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['service']['Connection']['DeleteConnection'](arg1);
}

export function GetCachedS3Client(arg1) {
  return window['go']['service']['Connection']['GetCachedS3Client'](arg1);
}

export function GetConnectionDetail(arg1) {
  return window['go']['service']['Connection']['GetConnectionDetail'](arg1);
}

export function GetSavedConnectionList() {
  return window['go']['service']['Connection']['GetSavedConnectionList']();
}

export function GetTimeoutContext() {
  return window['go']['service']['Connection']['GetTimeoutContext']();
}

export function Init() {
  return window['go']['service']['Connection']['Init']();
}

export function InitAndCacheS3Client(arg1) {
  return window['go']['service']['Connection']['InitAndCacheS3Client'](arg1);
}

export function QueryEncryptionKey() {
  return window['go']['service']['Connection']['QueryEncryptionKey']();
}

export function SaveS3Connection(arg1) {
  return window['go']['service']['Connection']['SaveS3Connection'](arg1);
}

export function TestS3Connection(arg1) {
  return window['go']['service']['Connection']['TestS3Connection'](arg1);
}
