// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Object']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Object']['BuildSucess'](arg1);
}

export function GetTimeoutContext() {
  return window['go']['service']['Object']['GetTimeoutContext']();
}

export function Init() {
  return window['go']['service']['Object']['Init']();
}

export function InitAndCacheS3Client(arg1) {
  return window['go']['service']['Object']['InitAndCacheS3Client'](arg1);
}

export function ListObjects(arg1) {
  return window['go']['service']['Object']['ListObjects'](arg1);
}

export function QueryEncryptionKey() {
  return window['go']['service']['Object']['QueryEncryptionKey']();
}
