// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {s3} from '../models';
import {context} from '../models';

export function BuildFailed(arg1:string,arg2:string):Promise<models.BaseResponse>;

export function BuildSucess(arg1:any):Promise<models.BaseResponse>;

export function DeleteObjects(arg1:models.DeleteObjectsReq):Promise<models.BaseResponse>;

export function DownloadObjects(arg1:models.DownloadObjectsReq):Promise<models.BaseResponse>;

export function GetCachedS3Client(arg1:string):Promise<s3.Client>;

export function GetTimeoutContext():Promise<context.Context|context.CancelFunc>;

export function Init():Promise<void>;

export function InitAndCacheS3Client(arg1:string):Promise<s3.Client>;

export function ListObjects(arg1:models.ListObjectsReq):Promise<models.BaseResponse>;

export function PrepareForUploading(arg1:models.PrepareForUploadingReq):Promise<models.BaseResponse>;

export function QueryEncryptionKey():Promise<string>;
