// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMultipartUpload(arg1) {
  return window['go']['service']['Object']['AbortMultipartUpload'](arg1);
}

export function BuildFailed(arg1, arg2) {
  return window['go']['service']['Object']['BuildFailed'](arg1, arg2);
}

export function BuildSucess(arg1) {
  return window['go']['service']['Object']['BuildSucess'](arg1);
}

export function CompleteMultipartUpload(arg1) {
  return window['go']['service']['Object']['CompleteMultipartUpload'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['service']['Object']['CreateFolder'](arg1);
}

export function CreateMultipartUpload(arg1) {
  return window['go']['service']['Object']['CreateMultipartUpload'](arg1);
}

export function DeleteObjects(arg1) {
  return window['go']['service']['Object']['DeleteObjects'](arg1);
}

export function DownloadObjects(arg1) {
  return window['go']['service']['Object']['DownloadObjects'](arg1);
}

export function FixDatabaseLockd() {
  return window['go']['service']['Object']['FixDatabaseLockd']();
}

export function GetCachedS3Client(arg1) {
  return window['go']['service']['Object']['GetCachedS3Client'](arg1);
}

export function GetTimeoutContext() {
  return window['go']['service']['Object']['GetTimeoutContext']();
}

export function Init() {
  return window['go']['service']['Object']['Init']();
}

export function InitAndCacheS3Client(arg1) {
  return window['go']['service']['Object']['InitAndCacheS3Client'](arg1);
}

export function InitDbClient() {
  return window['go']['service']['Object']['InitDbClient']();
}

export function ListObjects(arg1) {
  return window['go']['service']['Object']['ListObjects'](arg1);
}

export function PutMultipartUpload(arg1, arg2) {
  return window['go']['service']['Object']['PutMultipartUpload'](arg1, arg2);
}

export function QueryEncryptionKey() {
  return window['go']['service']['Object']['QueryEncryptionKey']();
}

export function ServiceName() {
  return window['go']['service']['Object']['ServiceName']();
}
